"""Model representing the response for the /ask route."""

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class AskResponseModel(BaseModel):
    """Model representing the response for the /ask route."""

    model_config = ConfigDict(strict=True)

    status: bool = Field(
        ...,
        title="Request Status",
        description="Indicates whether the request was successful.",
        json_schema_extra={"example": True},
    )

    message: str = Field(
        ...,
        title="Request Message",
        description="A human-readable message providing information about the request status.",
        json_schema_extra={"example": "Generation successful."},
    )

    timestamp: datetime = Field(
        ...,
        title="Request Timestamp",
        description="Timestamp of the request with timezone info.",
        json_schema_extra={"example": "2024-07-28T22:30:10.103368+05:30"},
    )

    latency: float = Field(
        ...,
        title="Request Latency",
        description="Time taken to process the request in seconds. Present only for successful requests.",
        json_schema_extra={"example": 1.234},
    )

    answer: str | None = Field(
        None,
        title="Generated Answer",
        description="The answer generated by the chatbot. Present only for successful requests.",
        json_schema_extra={
            "example": "Bootstrap at PES University is a week-long (typically 5-day) series "
            "of activities for freshers, usually held before regular classes commence. "
            "Its main purpose is to help students socialize, make new friends, and "
            "network with batchmates and seniors. It also allows them to explore various "
            "academic branches through simple and engaging activities."
        },
    )

    steps: str | None = Field(
        None,
        title="Thought process for the thinking model",
        description="This field contains the though process and reason of the thinking model",
        json_schema_extra={
            "example": "The user is asking:"
            "- How is CGPA and SGPA calculated"
            "- What do they need to score in each subject in first sem to get a SGPA of 9+"
            "Let me go through the context to find relevant information about CGPA and SGPA calculation at PES University."

            "From the context, I can find several relevant posts:"

            "1. From the post titled 'CGPA' (https://www.reddit.com/r/PESU/comments/13wdtcl/cgpa_and_sgpa_calculator/): This post has a detailed explanation of how SGPA and CGPA are calculated at PESU."

            "Key details from this post:"
            "- SGPA is a weighted average of grades in a semester where the weights are the credits for that course"
            "- SGPA = sum(credits for course * grade obtained in course) / total credits in semester"
            "- CGPA is a weighted average of your SGPA, where the weights are the credits in that semester"
            "- CGPA = sum(credits in semester * SGPA in semester) / total credits across all semesters"
            "Based on this, I'll compose a clear, accurate answer about how CGPA/SGPA is calculated at PESU and what marks they need in each subject to get a SGPA of 9+."
        },
    )
