"""Writer side of the shared Qdrant collection contract.

``conf/collection.yaml`` is the one place the collection name, embedding model,
vector geometry and payload schema are written down. This service creates the
collection from it and refuses to write into one that disagrees, so that
``services/api`` can rely on what it reads.
"""

import os
from pathlib import Path
from typing import NamedTuple

import yaml
from langchain_core.embeddings import Embeddings
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, Modifier, SparseVectorParams, VectorParams


class ContractViolationError(RuntimeError):
    """Raised when the live collection, a payload, or the model disagrees with the contract."""


class Contract(NamedTuple):
    """Values read from conf/collection.yaml."""

    name: str  # from $QDRANT_COLLECTION, not from the yaml
    model: str
    size: int
    distance: str
    vector_name: str
    metadata: tuple[str, ...]
    # Empty when conf/collection.yaml declares no `sparse` block, which turns
    # the sparse checks off rather than failing.
    sparse_vector_name: str = ""
    sparse_modifier: str = ""
    sparse_model: str = ""


def contract_path() -> Path:
    """Locate conf/collection.yaml by walking up from this module.

    Deployed, the service is its own repository root and the file sits beside it
    at /app/conf/; in the monorepo the same walk reaches the repo root, where the
    single authored copy lives. Deploy and image builds vendor it into the
    service tree, because a `git subtree split` ships only services/<name>/.
    """
    found = [p for p in (b / "conf" / "collection.yaml" for b in Path(__file__).resolve().parents) if p.is_file()]
    if not found:
        raise ContractViolationError("conf/collection.yaml not found above app/contract.py.")
    # In a monorepo checkout the service-local copy left behind by an image
    # build sits below the authored one. Identical copies are fine; a stale copy
    # silently winning is the failure this contract exists to prevent, so say so.
    for other in found[1:]:
        if other.read_text() != found[0].read_text():
            raise ContractViolationError(
                f"Conflicting contracts: {found[0]} differs from {other}. The copy under "
                f"services/*/conf/ is generated by image builds -- refresh or delete it."
            )
    return found[0]


def load(collection: str | None = None) -> Contract:
    """Read the contract: shape from conf/collection.yaml, name from the environment.

    Args:
        collection: Collection name. Defaults to ``$QDRANT_COLLECTION``.

    Returns:
        The contract for that collection.

    Raises:
        ContractViolationError: If no collection name is available. Deliberately
            fatal rather than defaulting: a default would let a misconfigured
            deployment quietly read or write the wrong environment's data.
    """
    name = collection or os.getenv("QDRANT_COLLECTION")
    if not name:
        raise ContractViolationError(
            "QDRANT_COLLECTION is not set. The cluster holds more than one collection "
            "(ask-pesu-prod is what the deployed services use; ask-pesu-dev is for local work), "
            "so the name has to be supplied explicitly."
        )
    collection_config = yaml.safe_load(contract_path().read_text())["collection"]
    dense = collection_config["dense"]
    sparse = collection_config.get("sparse") or {}
    return Contract(
        name=name,
        model=dense["model"],
        size=int(dense["size"]),
        distance=str(dense["distance"]),
        vector_name=dense.get("vector_name", ""),
        metadata=tuple(collection_config["metadata"]),
        sparse_vector_name=sparse.get("vector_name", ""),
        sparse_modifier=str(sparse.get("modifier", "")),
        sparse_model=str(sparse.get("model", "")),
    )


def vectors_config(contract: Contract) -> VectorParams | dict[str, VectorParams]:
    """Qdrant vectors_config for creating the collection from the contract."""
    params = VectorParams(size=contract.size, distance=Distance(contract.distance))
    return {contract.vector_name: params} if contract.vector_name else params


def sparse_vectors_config(contract: Contract) -> dict[str, SparseVectorParams] | None:
    """Qdrant ``sparse_vectors_config`` for the contract, or None if none is contracted."""
    if not contract.sparse_vector_name:
        return None
    modifier = Modifier(contract.sparse_modifier) if contract.sparse_modifier else None
    return {contract.sparse_vector_name: SparseVectorParams(modifier=modifier)}


def ensure_collection(contract: Contract, client: QdrantClient) -> bool:
    """Bring the live collection into agreement with the contract, or refuse to run.

    This service owns the collection's existence: on a fresh environment nothing
    else creates it, which is why ``services/api`` refuses to start until this
    one has run at least once.

    Two paths. If the collection is absent it is created with exactly the
    contracted geometry. If it is already there its geometry is checked and any
    disagreement raises -- adapting to what is already stored is the one thing
    that must not happen, because the vectors already written were produced by
    the contracted model and cannot be compared against anything else.

    Args:
        contract: The loaded contract.
        client: Qdrant client, with manage rights if the collection may be absent.

    Returns:
        True if this call created the collection, False if it already existed
        and matched.

    Raises:
        ContractViolationError: If an existing collection disagrees with the
            contract.
    """
    if not client.collection_exists(contract.name):
        try:
            client.create_collection(
                collection_name=contract.name,
                vectors_config=vectors_config(contract),
                sparse_vectors_config=sparse_vectors_config(contract),
            )
        except Exception:
            # Two writers starting together can both see the collection absent,
            # and the loser of that race gets an error for a collection that now
            # exists. Tolerate exactly that case: if the collection still is not
            # there, the create failed for a real reason -- a bad URL, a key
            # without manage rights, a malformed vector config -- and swallowing
            # it would leave both services running against nothing.
            if not client.collection_exists(contract.name):
                raise
        else:
            return True
    validate_collection(contract, client)
    return False


def _sparse_mismatches(contract: Contract, client: QdrantClient) -> list[str]:
    """Check the contracted sparse vector against the live collection.

    Returns an empty list when no sparse vector is contracted, so a collection
    that predates hybrid retrieval is not failed for lacking one.

    The modifier is the part worth checking. Without ``idf`` the vector still
    exists and writes still succeed -- only the ranking is silently wrong,
    because Qdrant scores raw term frequency instead of weighting rare terms.
    """
    if not contract.sparse_vector_name:
        return []
    live = client.get_collection(contract.name).config.params.sparse_vectors or {}
    if contract.sparse_vector_name not in live:
        return [f"no sparse vector {contract.sparse_vector_name!r} (collection has {sorted(live)})"]
    modifier = getattr(live[contract.sparse_vector_name], "modifier", None)
    modifier = str(getattr(modifier, "value", modifier) or "")
    if modifier != contract.sparse_modifier:
        return [f"sparse modifier {modifier or 'unset'!r} != contracted {contract.sparse_modifier!r}"]
    return []


def validate_collection(contract: Contract, client: QdrantClient) -> None:
    """Check the live Qdrant collection against the contract, or raise."""
    if not client.collection_exists(contract.name):
        raise ContractViolationError(
            f"Qdrant collection {contract.name!r} does not exist. It is created on startup from "
            f"conf/collection.yaml; check QDRANT_URL, or the name in the contract."
        )
    vectors = client.get_collection(contract.name).config.params.vectors
    if contract.vector_name:
        if not isinstance(vectors, dict) or contract.vector_name not in vectors:
            found = sorted(vectors) if isinstance(vectors, dict) else ["<unnamed>"]
            raise ContractViolationError(
                f"Collection {contract.name!r} has no named vector {contract.vector_name!r}; it exposes {found}."
            )
        params = vectors[contract.vector_name]
    else:
        if isinstance(vectors, dict):
            raise ContractViolationError(
                f"Collection {contract.name!r} uses named vectors {sorted(vectors)}, "
                f"but the contract expects the unnamed vector."
            )
        params = vectors

    distance = str(getattr(params.distance, "value", params.distance))
    mismatches = []
    if params.size != contract.size:
        mismatches.append(f"vector size {params.size} != contracted {contract.size}")
    if distance != contract.distance:
        mismatches.append(f"distance {distance!r} != contracted {contract.distance!r}")
    mismatches += _sparse_mismatches(contract, client)
    if mismatches:
        raise ContractViolationError(
            f"Collection {contract.name!r} violates conf/collection.yaml: {'; '.join(mismatches)}. "
            f"Re-index the collection, or correct the contract."
        )


def validate_embedding(contract: Contract, embedding: Embeddings) -> None:
    """Check the loaded model is the contracted one, at the contracted width."""
    model_name = getattr(embedding, "model_name", None)
    if model_name is not None and model_name != contract.model:
        raise ContractViolationError(f"Embedding model {model_name!r} != contracted {contract.model!r}.")
    # Measured through the public interface: the two services wrap the
    # SentenceTransformer under different attribute names, so reaching for it
    # makes this check silently pass on whichever side does not match.
    width = len(embedding.embed_query("contract dimension probe"))
    if width != contract.size:
        raise ContractViolationError(
            f"Embedding model {contract.model!r} produces {width}-dim vectors, "
            f"but conf/collection.yaml contracts size {contract.size}."
        )


def validate_payload(contract: Contract, metadata: dict[str, object]) -> None:
    """Check a payload about to be written carries exactly the contracted keys."""
    written, contracted = set(metadata), set(contract.metadata)
    if written == contracted:
        return
    raise ContractViolationError(
        f"Payload for collection {contract.name!r} violates conf/collection.yaml: "
        f"missing {sorted(contracted - written)}, unexpected {sorted(written - contracted)}."
    )
