"""Writer side of the shared Qdrant collection contract.

``conf/collection.yaml`` is the one place the collection name, embedding model,
vector geometry and payload schema are written down. This service creates the
collection from it and refuses to write into one that disagrees, so that
``services/api`` can rely on what it reads.
"""

import os
from pathlib import Path
from typing import NamedTuple

import yaml
from langchain_core.embeddings import Embeddings
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams


class ContractViolationError(RuntimeError):
    """Raised when the live collection, a payload, or the model disagrees with the contract."""


class Contract(NamedTuple):
    """Values read from conf/collection.yaml."""

    name: str  # from $QDRANT_COLLECTION, not from the yaml
    model: str
    size: int
    distance: str
    vector_name: str
    metadata: tuple[str, ...]


def contract_path() -> Path:
    """Locate conf/collection.yaml by walking up from this module.

    Deployed, the service is its own repository root and the file sits beside it
    at /app/conf/; in the monorepo the same walk reaches the repo root, where the
    single authored copy lives. Deploy and image builds vendor it into the
    service tree, because a `git subtree split` ships only services/<name>/.
    """
    found = [p for p in (b / "conf" / "collection.yaml" for b in Path(__file__).resolve().parents) if p.is_file()]
    if not found:
        raise ContractViolationError("conf/collection.yaml not found above app/contract.py.")
    # In a monorepo checkout the service-local copy left behind by an image
    # build sits below the authored one. Identical copies are fine; a stale copy
    # silently winning is the failure this contract exists to prevent, so say so.
    for other in found[1:]:
        if other.read_text() != found[0].read_text():
            raise ContractViolationError(
                f"Conflicting contracts: {found[0]} differs from {other}. The copy under "
                f"services/*/conf/ is generated by image builds -- refresh or delete it."
            )
    return found[0]


def load(collection: str | None = None) -> Contract:
    """Read the contract: shape from conf/collection.yaml, name from the environment.

    Args:
        collection: Collection name. Defaults to ``$QDRANT_COLLECTION``.

    Returns:
        The contract for that collection.

    Raises:
        ContractViolationError: If no collection name is available. Deliberately
            fatal rather than defaulting: a default would let a misconfigured
            deployment quietly read or write the wrong environment's data.
    """
    name = collection or os.getenv("QDRANT_COLLECTION")
    if not name:
        raise ContractViolationError(
            "QDRANT_COLLECTION is not set. One cluster holds one collection per environment "
            "(e.g. ask-pesu-prod, ask-pesu-dev), so the name has to be supplied explicitly."
        )
    collection_config = yaml.safe_load(contract_path().read_text())["collection"]
    dense = collection_config["dense"]
    return Contract(
        name=name,
        model=dense["model"],
        size=int(dense["size"]),
        distance=str(dense["distance"]),
        vector_name=dense.get("vector_name", ""),
        metadata=tuple(collection_config["metadata"]),
    )


def vectors_config(contract: Contract) -> VectorParams | dict[str, VectorParams]:
    """Qdrant vectors_config for creating the collection from the contract."""
    params = VectorParams(size=contract.size, distance=Distance(contract.distance))
    return {contract.vector_name: params} if contract.vector_name else params


def ensure_collection(contract: Contract, client: QdrantClient) -> bool:
    """Create the collection from the contract if absent, else validate it. True if created."""
    if not client.collection_exists(contract.name):
        try:
            client.create_collection(collection_name=contract.name, vectors_config=vectors_config(contract))
        except Exception:
            # Lost a race with another starting writer. Tolerate only that: if
            # the collection still is not there, the create failed for a real
            # reason and must not be swallowed -- which is what the previous
            # bare try/except did, reporting everything as "already exists".
            if not client.collection_exists(contract.name):
                raise
        else:
            return True
    validate_collection(contract, client)
    return False


def validate_collection(contract: Contract, client: QdrantClient) -> None:
    """Check the live Qdrant collection against the contract, or raise."""
    if not client.collection_exists(contract.name):
        raise ContractViolationError(
            f"Qdrant collection {contract.name!r} does not exist. It is created on startup from "
            f"conf/collection.yaml; check QDRANT_URL, or the name in the contract."
        )
    vectors = client.get_collection(contract.name).config.params.vectors
    if contract.vector_name:
        if not isinstance(vectors, dict) or contract.vector_name not in vectors:
            found = sorted(vectors) if isinstance(vectors, dict) else ["<unnamed>"]
            raise ContractViolationError(
                f"Collection {contract.name!r} has no named vector {contract.vector_name!r}; it exposes {found}."
            )
        params = vectors[contract.vector_name]
    else:
        if isinstance(vectors, dict):
            raise ContractViolationError(
                f"Collection {contract.name!r} uses named vectors {sorted(vectors)}, "
                f"but the contract expects the unnamed vector."
            )
        params = vectors

    distance = str(getattr(params.distance, "value", params.distance))
    mismatches = []
    if params.size != contract.size:
        mismatches.append(f"vector size {params.size} != contracted {contract.size}")
    if distance != contract.distance:
        mismatches.append(f"distance {distance!r} != contracted {contract.distance!r}")
    if mismatches:
        raise ContractViolationError(
            f"Collection {contract.name!r} violates conf/collection.yaml: {'; '.join(mismatches)}. "
            f"Re-index the collection, or correct the contract."
        )


def validate_embedding(contract: Contract, embedding: Embeddings) -> None:
    """Check the loaded model is the contracted one, at the contracted width."""
    model_name = getattr(embedding, "model_name", None)
    if model_name is not None and model_name != contract.model:
        raise ContractViolationError(f"Embedding model {model_name!r} != contracted {contract.model!r}.")
    # Measured through the public interface: the two services wrap the
    # SentenceTransformer under different attribute names, so reaching for it
    # makes this check silently pass on whichever side does not match.
    width = len(embedding.embed_query("contract dimension probe"))
    if width != contract.size:
        raise ContractViolationError(
            f"Embedding model {contract.model!r} produces {width}-dim vectors, "
            f"but conf/collection.yaml contracts size {contract.size}."
        )


def validate_payload(contract: Contract, metadata: dict[str, object]) -> None:
    """Check a payload about to be written carries exactly the contracted keys."""
    written, contracted = set(metadata), set(contract.metadata)
    if written == contracted:
        return
    raise ContractViolationError(
        f"Payload for collection {contract.name!r} violates conf/collection.yaml: "
        f"missing {sorted(contracted - written)}, unexpected {sorted(written - contracted)}."
    )
